Local_bus_information_system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'OutletMapController@index');

Route::get('/routing', 'OutletMapController@routing');

Route::post('/', 'OutletMapController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
 * Outlets Routes
 */
Route::get('/our_outlets', 'OutletMapController@index')->name('outlet_map.index');
Route::resource('outlets', 'OutletController');

/*
 * Stops Routes
 */
Route::resource('stops', 'StopController');

/*
 * Buses Routes
 */
Route::resource('buses', 'BusController');

/*
 * Trip Routes
 */
Route::resource('trips', 'TripController');

/*Route::get('/about', 'PageController@index');

Local_bus_information_system/resources/views/buses/create.blade.php
@extends('layouts.app')

@section('title', __('bus.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('bus.create') }}</div>
            <form method="POST" action="{{ route('buses.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('bus.name') }}</label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="owner" class="control-label">{{ __('bus.owner') }}</label>
                        <input id="owner" type="text" class="form-control{{ $errors->has('owner') ? ' is-invalid' : '' }}" name="owner" value="{{ old('owner') }}" required>
                        {!! $errors->first('owner', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="number" class="control-label">{{ __('bus.number') }}</label>
                                <input id="number" type="text" class="form-control{{ $errors->has('number') ? ' is-invalid' : '' }}" name="number" value="{{ old('number', request('number')) }}">
                                {!! $errors->first('number', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="type" class="control-label">{{ __('bus.type') }}</label>
                                <select id="type" class="form-control{{ $errors->has('type') ? ' is-invalid' : '' }}" name="type" required>
                                    <option value="ORD" @if(old('type', request('type')) == 'ORD') selected="" @endif>ORD</option>
                                    <option value="LF" @if(old('type', request('type')) == 'LF') selected="" @endif>LF</option>
                                    <option value="LS" @if(old('type', request('type')) == 'LS') selected="" @endif>LS</option>
                                    <option value="FP" @if(old('type', request('type')) == 'FP') selected="" @endif>FP</option>
                                    <option value="SFP" @if(old('type', request('type')) == 'SFP') selected="" @endif>SFP</option>
                                </select>
                                
                                {!! $errors->first('type', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                    </div>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('bus.create') }}" class="btn btn-success">
                    <a href="{{ route('buses.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

Local_bus_information_system/resources/views/buses/edit.blade.php
@extends('layouts.app')

@section('title', __('bus.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $bus)

            <div class="card">
                <div class="card-header">{{ __('bus.delete') }}</div>
                <div class="card-body">
                    <label class="control-label text-primary">{{ __('bus.name') }}</label>
                    <p>{{ $bus->name }}</p>
                    <label class="control-label text-primary">{{ __('bus.owner') }}</label>
                    <p>{{ $bus->owner }}</p>
                    <label class="control-label text-primary">{{ __('bus.number') }}</label>
                    <p>{{ $bus->number }}</p>
                    <label class="control-label text-primary">{{ __('bus.type') }}</label>
                    <p>{{ $bus->type }}</p>
                    {!! $errors->first('bus_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('bus.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('buses.destroy', $bus) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="bus_id" type="hidden" value="{{ $bus->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('buses.edit', $bus) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>

        @else
        <div class="card">
            <div class="card-header">{{ __('bus.edit') }}</div>
            <form method="POST" action="{{ route('buses.update', $bus) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('bus.name') }}</label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $bus->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="owner" class="control-label">{{ __('bus.owner') }}</label>
                        <input id="owner" type="text" class="form-control{{ $errors->has('owner') ? ' is-invalid' : '' }}" name="owner" value="{{ old('owner', $bus->owner) }}" required>
                        {!! $errors->first('owner', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="number" class="control-label">{{ __('bus.number') }}</label>
                                <input id="number" type="text" class="form-control{{ $errors->has('number') ? ' is-invalid' : '' }}" name="number" value="{{ old('number', $bus->number) }}" required>
                                {!! $errors->first('number', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="type" class="control-label">{{ __('bus.type') }}</label>
                                <select id="type" class="form-control{{ $errors->has('type') ? ' is-invalid' : '' }}" name="type" required>
                                    <option value="ORD" @if(old('type', $bus->type) == 'ORD') selected="" @endif>ORD</option>
                                    <option value="LF" @if(old('type', $bus->type) == 'LF') selected="" @endif>LF</option>
                                    <option value="LS" @if(old('type', $bus->type) == 'LS') selected="" @endif>LS</option>
                                    <option value="FP" @if(old('type', $bus->type) == 'FP') selected="" @endif>FP</option>
                                    <option value="SFP" @if(old('type', $bus->type) == 'SFP') selected="" @endif>SFP</option>
                                </select>
                                
                                {!! $errors->first('type', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                    </div>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('bus.update') }}" class="btn btn-success">
                    <a href="{{ route('buses.show', $bus) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    
                        <a href="{{ route('buses.edit', [$bus, 'action' => 'delete']) }}" id="del-bus-{{ $bus->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

Local_bus_information_system/resources/views/buses/list.blade.php
@extends('layouts.app')

@section('title', __('bus.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
            <a href="{{ route('buses.create') }}" class="btn btn-success">{{ __('bus.create') }}</a>
    </div>
    <h1 class="page-title">{{ __('bus.list') }} <small>{{ __('app.total') }} : {{ $buses->total() }} {{ __('bus.bus') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="control-label">{{ __('bus.search') }}</label>
                        <input placeholder="{{ __('bus.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('bus.search') }}" class="btn btn-secondary">
                    <a href="{{ route('buses.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('bus.name') }}</th>
                        <th>{{ __('bus.owner') }}</th>
                        <th>{{ __('bus.number') }}</th>
                        <th>{{ __('bus.type') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($buses as $key => $bus)
                    <tr>
                        <td class="text-center">{{ $buses->firstItem() + $key }}</td>
                        <td>{!! $bus->name !!}</td>
                        <td>{{ $bus->owner }}</td>
                        <td>{{ $bus->number }}</td>
                        <td>{{ $bus->type }}</td>
                        <td class="text-center">
                            <a href="{{ route('buses.show', $bus) }}" id="show-outlet-{{ $bus->id }}">{{ __('app.show') }}</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $buses->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

Local_bus_information_system/resources/views/buses/show.blade.php
@extends('layouts.app')

@section('title', __('bus.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('bus.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('bus.name') }}</td><td>{{ $bus->name }}</td></tr>
                        <tr><td>{{ __('bus.owner') }}</td><td>{{ $bus->owner }}</td></tr>
                        <tr><td>{{ __('bus.number') }}</td><td>{{ $bus->number }}</td></tr>
                        <tr><td>{{ __('bus.type') }}</td><td>{{ $bus->type }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                    <a href="{{ route('buses.edit', $bus) }}" id="edit-outlet-{{ $bus->id }}" class="btn btn-warning">{{ __('bus.edit') }}</a>
                <a href="{{ route('buses.index') }}" class="btn btn-link">{{ __('bus.back_to_index') }}</a>
            </div>
        </div>
    </div>
    {{--<div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ trans('bus.location') }}</div>
            @if ($bus->longitude)
            <div class="card-body" id="mapid"></div>
            @else
            <div class="card-body">{{ __('bus.no_coordinate') }}</div>
            @endif
        </div>
    </div>--}}
</div>
@endsection

@section('styles')


<style>
    #mapid { height: 400px; }
</style>
@endsection