Local_bus_information_system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'OutletMapController@index');

Route::get('/routing', 'OutletMapController@routing');

Route::post('/', 'OutletMapController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
 * Outlets Routes
 */
Route::get('/our_outlets', 'OutletMapController@index')->name('outlet_map.index');
Route::resource('outlets', 'OutletController');

/*
 * Stops Routes
 */
Route::resource('stops', 'StopController');

/*
 * Buses Routes
 */
Route::resource('buses', 'BusController');

/*
 * Trip Routes
 */
Route::resource('trips', 'TripController');

/*Route::get('/about', 'PageController@index');

Local_bus_information_system/app/Trip.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trip extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'bus_id', 'start', 'end', 'start_lat', 'start_long', 'end_lat', 'end_long', 'stops_details',
    ];

    /*public $appends = [
        'start_lat', 'start_long', 'end_lat', 'end_long', 'stops_details',
    ];

    public function setStartLatAttribute()
    {
        $this->attributes['start_lat'] = $this->origin->latitude;
    }

    public function setStartLongAttribute()
    {
        $this->attributes['start_long'] = $this->origin->longitude;
    }

    public function setEndLatAttribute()
    {
        $this->attributes['end_lat'] = $this->destination->latitude;
    }

    public function setEndLongAttribute()
    {
        $this->attributes['end_long'] = $this->destination->longitude;
    }

    public function setStopsDetailsAttribute()
    {
        $this->attributes['stops_details'] = 'sdfsdf';
    }*/
}

Local_bus_information_system/app/Http/Controllers/TripController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Bus;
use App\Stop;
use App\Trip;

class TripController extends Controller
{
    public function __construct() {

    	$this->middleware('auth');

    }

    public function index()
    {
        /*$tripQuery = Trip::query();
        $tripQuery->where('name', 'like', '%'.request('q').'%');
        $trips = $tripQuery->paginate(25);*/
        $stops = Stop::all();
        $trips = Trip::leftJoin('stops', function($join) {
                  $join->on('trips.start_lat', '=', 'stops.latitude');
                  $join->on('trips.start_long', '=', 'stops.longitude');
                })->leftJoin('stops as s', function($join) {
                  $join->on('trips.end_lat', '=', 's.latitude');
                  $join->on('trips.end_long', '=', 's.longitude');
                })->leftJoin('buses as b', 'b.id', '=', 'trips.bus_id')->paginate(25, ['trips.*', 'b.name', 'b.owner', 'b.number', 'b.type', 'stops.name as origin', 's.name as destination']);
                

                
            //dd($trips);
        return view('trips.list', [
            'trips' => $trips
        ]);
    }

    public function create()
    {
    	$stops = Stop::orderBy('name')->get();
    	$buses = Bus::all();
        return view('trips.create', [
        	'stops' => $stops ,
        	'buses' => $buses 
        ]);
    }

    public function store(Request $request)
    {

        $newTrip = $request->validate([
        	'bus_id'     => 'required|integer',
            'start'      => 'required|max:191',
            'end'     	 => 'required|max:191',
            'from'     	 => 'required|max:191',
            'to'     	 => 'required|max:191',
        ]);

        $origin = Stop::find($request->from);
        $destination = Stop::find($request->to);

        $newTrip['start_lat'] = $origin->latitude;
        $newTrip['start_long'] = $origin->longitude;

		$newTrip['end_lat'] = $destination->latitude;
        $newTrip['end_long'] = $destination->longitude;        

        //$newTrip['bus_id'] = 1;
        $stopDetails = [];
        $stopDetails[$request->start][] = $origin->latitude;
        $stopDetails[$request->start][] = $origin->longitude;
        $newTrip['stops_details'] = json_encode($stopDetails);

        //$request->start_lat = $origin

        $trip = Trip::create($newTrip);

        return redirect('/trips');
    }

    public function show($trip)
    {
    	$trip = Trip::leftJoin('stops', function($join) {
                  $join->on('trips.start_lat', '=', 'stops.latitude');
                  $join->on('trips.start_long', '=', 'stops.longitude');
                })->leftJoin('stops as s', function($join) {
                  $join->on('trips.end_lat', '=', 's.latitude');
                  $join->on('trips.end_long', '=', 's.longitude');
                })->leftJoin('buses as b', 'b.id', '=', 'trips.bus_id')->where('trips.id', $trip)->get(['trips.*', 'b.name', 'b.owner', 'b.number', 'b.type', 'stops.name as origin', 's.name as destination'])->first();

        return view('trips.show', compact('trip'));
    }

    public function edit($trip)
    {
        $trip = Trip::leftJoin('stops', function($join) {
                  $join->on('trips.start_lat', '=', 'stops.latitude');
                  $join->on('trips.start_long', '=', 'stops.longitude');
                })->leftJoin('stops as s', function($join) {
                  $join->on('trips.end_lat', '=', 's.latitude');
                  $join->on('trips.end_long', '=', 's.longitude');
                })->leftJoin('buses as b', 'b.id', '=', 'trips.bus_id')->where('trips.id', $trip)->get(['trips.*', 'b.name', 'b.owner', 'b.number', 'b.type', 'stops.name as origin', 's.name as destination', 'stops.id as originid', 's.id as destid'])->first();

        $trip->stopsdet = json_decode($trip->stops_details);

        $stops = Stop::orderBy('name')->get();
        $buses = Bus::all();

        return view('trips.edit', [
            'trip' 	=> $trip,
            'buses' => $buses,
            'stops' => $stops
        ]);
    }

    public function update(Request $request, Trip $trip)
    {

    	//dd($request->sstop);
        $tripData = $request->validate([
        	'bus_id'     => 'required|integer',
            'start'      => 'required|max:191',
            'end'     	 => 'required|max:191',
            'from'     	 => 'required|max:191',
            'to'     	 => 'required|max:191',
        ]);

        $origin = Stop::find($request->from);
        $destination = Stop::find($request->to);

        $tripData['start_lat'] = $origin->latitude;
        $tripData['start_long'] = $origin->longitude;

		$tripData['end_lat'] = $destination->latitude;
        $tripData['end_long'] = $destination->longitude;        

        //$tripData['bus_id'] = 1;
        $stopDetails = [];

        $stops = Stop::all()->keyBy('id');

        if(count($request->stime)>0) {
        	foreach ($request->stime as $key => $value) {
	        	/*echo $value . " => " . $stops[$request->sstop[$key]]->latitude . ' ('. $request->sstop[$key] .')';
	        	echo PHP_EOL;*/
	        	$stopDetails[$value][] =  $stops[$request->sstop[$key]]->latitude;
	        	$stopDetails[$value][] =  $stops[$request->sstop[$key]]->longitude;
	        }
        }
        else {

        	$stopDetails[$request->start][] = $origin->latitude;
        	$stopDetails[$request->start][] = $origin->longitude;

        }

        $tripData['stops_details'] = json_encode($stopDetails);
		
		$trip->update($tripData);

        return redirect('/trips');
    }

    public function destroy(Request $request, Trip $trip)
    {

        $request->validate(['Trip_id' => 'required']);

        if ($request->get('Trip_id') == $trip->id && $trip->delete()) {
            return redirect()->route('trips.index');
        }

        return back();
    }
}

Local_bus_information_system/resources/views/trips/create.blade.php
@extends('layouts.app')

@section('title', __('trip.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('trip.create') }}</div>
            <form method="POST" action="{{ route('trips.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="bus_id" class="control-label">{{ __('trip.bus') }}</label>
                        <select id="bus_id" class="form-control{{ $errors->has('bus_id') ? ' is-invalid' : '' }}" name="bus_id" required>
                            @foreach($buses as $bus)
                            <option value="{{$bus->id}}" @if(old('bus_id', request('bus_id')) == $bus->id) selected="" @endif>{{$bus->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('trip.start') }} (format hh:mm:ss    eg: 19:00:00.000000)</label>
                        <input id="start" type="text" class="form-control{{ $errors->has('start') ? ' is-invalid' : '' }}" name="start" value="{{ old('start', '19:00:00.000000') }}" required>
                        {!! $errors->first('start', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('trip.end') }} (format hh:mm:ss    eg: 19:00:00.000000)</label>
                        <input id="end" type="text" class="timepicker form-control{{ $errors->has('end') ? ' is-invalid' : '' }}" name="end" value="{{ old('end', '20:00:00.000000') }}" required>
                        {!! $errors->first('end', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="from" class="control-label">{{ __('trip.from') }}</label>
                        <select id="from" class="form-control{{ $errors->has('from') ? ' is-invalid' : '' }}" name="from" required>
                            @foreach($stops as $stop)
                            <option value="{{$stop->id}}" @if(old('from', request('from')) == $stop->id) selected="" @endif>{{$stop->name}}</option>
                            @endforeach
                        </select>
                        
                        {!! $errors->first('from', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="to" class="control-label">{{ __('trip.to') }}</label>
                        <select id="to" class="form-control{{ $errors->has('to') ? ' is-invalid' : '' }}" name="to" required>
                            @foreach($stops as $stop)
                            <option value="{{$stop->id}}" @if(old('to', request('to')) == $stop->id) selected="" @endif>{{$stop->name}}</option>
                            @endforeach
                        </select>
                        
                        {!! $errors->first('to', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('trip.create') }}" class="btn btn-success">
                    <a href="{{ route('trips.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>


@endsection

@section('styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
{{--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>  

  <script type="text/javascript">
    $(function(){
    $('.timepicker').datetimepicker({
        format: 'HH:mm:ss'
    });
    });
</script>
--}}
@endsection

@push('scripts')
{{--<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>        
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.4.0/lang/en-gb.js"></script>                
<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.0.0/js/bootstrap-datetimepicker.min.js"></script>

<script>
jQuery(document).ready(function () {

    jQuery('.timepicker').datetimepicker({ format: 'LT' });
    //jQuery('.timepicker').datetimepicker();

});
</script>--}}
@endpush

Local_bus_information_system/resources/views/trips/edit.blade.php
@extends('layouts.app')

@section('title', __('trip.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        @php $count = 0; @endphp
        @if (request('action') == 'delete' && $trip)

            <div class="card">
                <div class="card-header">{{ __('trip.delete') }}</div>
                <div class="card-body">
                    <label class="control-label text-primary">{{ __('trip.bus') }}</label>
                    <p>{{ $trip->name }}</p>
                    <label class="control-label text-primary">{{ __('trip.start') }}</label>
                    <p>{{date('h:i:s a', strtotime($trip->start))}}</p>
                    <label class="control-label text-primary">{{ __('trip.end') }}</label>
                    <p>{{date('h:i:s a', strtotime($trip->end))}}</p>
                    <label class="control-label text-primary">{{ __('trip.type') }}</label>
                    <p>{{ $trip->type }}</p>
                    <label class="control-label text-primary">{{ __('trip.from') }}</label>
                    <p>{{ $trip->origin }}</p>
                    <label class="control-label text-primary">{{ __('trip.to') }}</label>
                    <p>{{ $trip->destination }}</p>
                    {!! $errors->first('bus_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('trip.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('trips.destroy', $trip) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="Trip_id" type="hidden" value="{{ $trip->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('trips.edit', $trip) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>

        @else
        <div class="card">
            <div class="card-header">{{ __('trip.edit') }}</div>
            <form method="POST" action="{{ route('trips.update', $trip) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="bus_id" class="control-label">{{ __('trip.bus') }}</label>
                        <select id="bus_id" class="form-control{{ $errors->has('bus_id') ? ' is-invalid' : '' }}" name="bus_id" required>
                            @foreach($buses as $bus)
                            <option value="{{$bus->id}}" @if(old('bus_id', $trip->bus_id) == $bus->id) selected="" @endif>{{$bus->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="start" class="control-label">{{ __('trip.start') }}</label>
                        <input id="start" type="text" class="form-control{{ $errors->has('start') ? ' is-invalid' : '' }}" name="start" value="{{ old('start', $trip->start) }}" required>
                        {!! $errors->first('start', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="end" class="control-label">{{ __('trip.end') }}</label>
                        <input id="end" type="text" class="form-control{{ $errors->has('owner') ? ' is-invalid' : '' }}" name="end" value="{{ old('end', $trip->end) }}" required>
                        {!! $errors->first('end', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>

                    <div class="form-group">
                        <label for="from" class="control-label">{{ __('trip.from') }}</label>
                        <select id="from" class="form-control{{ $errors->has('from') ? ' is-invalid' : '' }}" name="from" required>
                            <option value=''>select...</option>
                            @foreach($stops as $stop)
                            <option value="{{$stop->id}}" @if(old('from', $trip->originid) == $stop->id) selected="" @endif>{{$stop->name}}</option>
                            @endforeach
                        </select>
                        
                        {!! $errors->first('from', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="to" class="control-label">{{ __('trip.to') }}</label>
                        <select id="to" class="form-control{{ $errors->has('to') ? ' is-invalid' : '' }}" name="to" required>
                            <option value=''>select...</option>
                            @foreach($stops as $stop)
                            <option value="{{$stop->id}}" @if(old('to', $trip->destid) == $stop->id) selected="" @endif>{{$stop->name}}</option>
                            @endforeach
                        </select>
                        
                        {!! $errors->first('to', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    
                    
                    <!--<div class="input-group form-group">
                        <div class="input-group-prepend">
                        </div>
                        
                        <input autocomplete="off" class="form-control" id="field1" name="prof1" type="text" placeholder="Type something" data-items="8"/>

                    </div>-->
                    <div id="field">
                        
                        @isset($trip->stopsdet)
                            @foreach($trip->stopsdet as $key => $stopDetail)
                                <div class="form-row" id="field{{$loop->iteration}}">

                                    <div class="form-group col-md-6">
                                        <label for="inputZip">Time</label>
                                        <div class="input-group">
                                            @if(!$loop->first)
                                            <div class="input-group-prepend">
                                              <button id="remove{{$loop->iteration}}" class="btn btn-danger remove-mee">-</button>
                                            </div>
                                            @endif
                                            <input type="text" class="form-control" id="inlineFormInputGroupTme{{$loop->iteration}}" placeholder="time" value="{{ $key }}" name="stime[]">
                                        </div>
                                    </div>
                                    <div class="form-group col-md-6">
                                      <label for="inputState">Stop</label>
                                      <select id="inputState{{$loop->iteration}}" class="form-control" name="sstop[]">

                                        @foreach($stops as $stop)
                                            <option value="{{$stop->id}}" @if(($stopDetail[0] == $stop->latitude) && ($stopDetail[1] == $stop->longitude)) selected="" @endif>{{$stop->name}}</option>
                                        @endforeach
                                      </select>
                                    </div>
                                </div>
                                @php $count++; @endphp
                            @endforeach
                        @endisset
                    </div>

                    <button type="button" class="btn btn-lg btn-block add-more">+</button>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('trip.update') }}" class="btn btn-success">
                    <a href="{{ route('trips.show', $trip) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    
                        <a href="{{ route('trips.edit', [$trip, 'action' => 'delete']) }}" id="del-bus-{{ $trip->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    
                </div>
            </form>
        </div>
    </div>
</div>
@endif
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
    var next = {{$count}};
    $(".add-more").click(function(e){
        e.preventDefault();
         var addto = "#field";
        var addRemove = "#field" + (next);
        next = next + 1;
        //var newIn = '<div class="input-group form-group"><div class="input-group-prepend"><button id="remove' + (next - 1) + '" class="btn btn-danger remove-me" >-</button></div><input autocomplete="off" class="form-control" id="field' + next + '" name="field' + next + '" type="text"></div>';
        var newIn = '<div class="form-row" id="field' + next + '"> <div class="form-group col-md-6"> <label for="inputZip">Time</label> <div class="input-group"> <div class="input-group-prepend"> <button id="remove' + (next) + '" class="btn btn-danger remove-me">-</button> </div> <input type="text" class="form-control" id="inlineFormInputGrouptime' + next + '" placeholder="time" name="stime[]"> </div> </div> <div class="form-group col-md-6"> <label for="inputState">Stop</label> <select id="inputStop' + next + '" class="form-control" name="sstop[]"> @foreach($stops as $stop)<option value="{{$stop->id}}">{{$stop->name}}</option> @endforeach </select> </div> </div>';
        var newInput = $(newIn);
        //var removeBtn = '<div class="input-group-prepend"><button id="remove' + (next - 1) + '" class="btn btn-danger remove-me" >-</button></div>';
        //var removeButton = $(removeBtn);
        $(addto).append(newInput);
        //$(addRemove).after(removeButton);
        $("#field" + next).attr('data-source',$(addto).attr('data-source'));
        $("#count").val(next);  
        
            $('.remove-me').click(function(e){
                e.preventDefault();
                var fieldNum = this.id.charAt(this.id.length-1);
                var fieldID = "#field" + fieldNum;
                $(this).remove();
                $(fieldID).remove();
            });
    });
    

    $('.remove-mee').click(function(e){
                e.preventDefault();
                var fieldNum = this.id.charAt(this.id.length-1);
                var fieldID = "#field" + fieldNum;
                $(this).remove();
                $(fieldID).remove();
            });
});


</script>
@endsection

Local_bus_information_system/resources/views/trips/list.blade.php
@extends('layouts.app')

@section('title', __('trip.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
            <a href="{{ route('trips.create') }}" class="btn btn-success">{{ __('trip.create') }}</a>
    </div>
    <h1 class="page-title">{{ __('trip.list') }} <small>{{ __('app.total') }} : {{ $trips->total() }} {{ __('trip.trip') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                {{--<form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="control-label">{{ __('trip.search') }}</label>
                        <input placeholder="{{ __('trip.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('trip.search') }}" class="btn btn-secondary">
                    <a href="{{ route('trips.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>--}}
            </div>
            <table class="table table-sm table-responsive-sm">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('trip.start') }}</th>
                        <th>{{ __('trip.end') }}</th>
                        <th>{{ __('trip.from') }}</th>
                        <th>{{ __('trip.to') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($trips as $key => $trip)
                    <tr>
                        <td class="text-center">{{ $trips->firstItem() + $key }}</td>
                        <td>{{date('h:i:s a', strtotime($trip->start))}}</td>
                        <td>{{date('h:i:s a', strtotime($trip->end))}}</td>
                        <td>{{ $trip->origin }}</td>
                        <td>{{ $trip->destination }}</td>
                        <td class="text-center">
                            <a href="{{ route('trips.show', $trip) }}" id="show-outlet-{{ $trip->id }}">{{ __('app.show') }}</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $trips->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

Local_bus_information_system/resources/views/trips/show.blade.php
@extends('layouts.app')

@section('title', __('trip.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('trip.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        
                        <tr><td>{{ __('bus.name') }}</td><td>{{ $trip->name }}</td></tr>
                        <tr><td>{{ __('bus.owner') }}</td><td>{{ $trip->owner }}</td></tr>
                        <tr><td>{{ __('bus.number') }}</td><td>{{ $trip->number }}</td></tr>
                        <tr><td>{{ __('bus.type') }}</td><td>{{ $trip->type }}</td></tr>
                        <tr><td>{{ __('trip.start') }}</td><td>{{ $trip->start }}</td></tr>
                        <tr><td>{{ __('trip.end') }}</td><td>{{ $trip->end }}</td></tr>
                        <tr><td>{{ __('trip.from') }}</td><td>{{ $trip->origin }}</td></tr>
                        <tr><td>{{ __('trip.to') }}</td><td>{{ $trip->destination }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                    <a href="{{ route('trips.edit', $trip) }}" id="edit-outlet-{{ $trip->id }}" class="btn btn-warning">{{ __('trip.edit') }}</a>
                <a href="{{ route('trips.index') }}" class="btn btn-link">{{ __('trip.back_to_index') }}</a>
            </div>
        </div>
    </div>
    {{--<div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ trans('trip.location') }}</div>
            @if ($trip->longitude)
            <div class="card-body" id="mapid"></div>
            @else
            <div class="card-body">{{ __('trip.no_coordinate') }}</div>
            @endif
        </div>
    </div>--}}
</div>
@endsection

@section('styles')


<style>
    #mapid { height: 400px; }
</style>
@endsection