Local_bus_information_system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'OutletMapController@index');

Route::get('/routing', 'OutletMapController@routing');

Route::post('/', 'OutletMapController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
 * Outlets Routes
 */
Route::get('/our_outlets', 'OutletMapController@index')->name('outlet_map.index');
Route::resource('outlets', 'OutletController');

/*
 * Stops Routes
 */
Route::resource('stops', 'StopController');

/*
 * Buses Routes
 */
Route::resource('buses', 'BusController');

/*
 * Trip Routes
 */
Route::resource('trips', 'TripController');

/*Route::get('/about', 'PageController@index');

Local_bus_information_system/app/Outlet.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Outlet extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'address', 'latitude', 'longitude', 'creator_id',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    public $appends = [
        'coordinate', 'map_popup_content',
    ];

    /**
     * Get outlet name_link attribute.
     *
     * @return string
     */
    public function getNameLinkAttribute()
    {
        $title = __('app.show_detail_title', [
            'name' => $this->name, 'type' => __('outlet.outlet'),
        ]);
        $link = '<a href="'.route('outlets.show', $this).'"';
        $link .= ' title="'.$title.'">';
        $link .= $this->name;
        $link .= '</a>';

        return $link;
    }

    /**
     * Outlet belongs to User model relation.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get outlet coordinate attribute.
     *
     * @return string|null
     */
    public function getCoordinateAttribute()
    {
        if ($this->latitude && $this->longitude) {
            return $this->latitude.', '.$this->longitude;
        }
    }

    /**
     * Get outlet map_popup_content attribute.
     *
     * @return string
     */
    public function getMapPopupContentAttribute()
    {
        $mapPopupContent = '';
        $mapPopupContent .= '<div class="my-2"><strong>'.__('outlet.name').':</strong><br>'.$this->name_link.'</div>';
        $mapPopupContent .= '<div class="my-2"><strong>'.__('outlet.coordinate').':</strong><br>'.$this->coordinate.'</div>';

        return $mapPopupContent;
    }
}

Local_bus_information_system/app/Http/Controllers/Api/OutletController.php
<?php
namespace App\Http\Controllers\Api;
use App\Outlet;
use App\Trip;
use App\Stop;
use App\LiveData;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Resources\Outlet as OutletResource;
use \stdClass;
use Illuminate\Support\Collection;
class OutletController extends Controller
{
    /**
     * Get outlet listing on Leaflet JS geoJSON data structure.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Illuminate\Http\JsonResponse
     */
    public function index(Request $request)
    {
        $from = date('H:i:s');
        //$stops = Trip::whereBetween('start', ['00:00:000', $from])->orWhereBetween('start', [$from, '23:59:59'])->get(); 
        $outlets = Trip::leftJoin('stops', function($join) {
                      $join->on('trips.start_lat', '=', 'stops.latitude');
                      $join->on('trips.start_long', '=', 'stops.longitude');
                    })->leftJoin('stops as s', function($join) {
                      $join->on('trips.end_lat', '=', 's.latitude');
                      $join->on('trips.end_long', '=', 's.longitude');
                    })->whereTime('start', '<=', $from)
                    ->WhereTime('end', '>=', $from)->get(['trips.*', 'stops.name as origin', 's.name as destination']); 
        $collection = new Collection();
        $final = new stdClass();
        foreach ($outlets as $key => $value) {
            $stops = json_decode($value->stops_details);
            foreach ($stops as $keyy => $val) {
                if(strtotime($keyy) >= strtotime($from)) {
                    $final->latitude = $val[0];
                    $final->longitude = $val[1];
                    $value->time = date('h:i:s a', strtotime($keyy));
                    $value->name = Stop::where('latitude', $val[0])->where('longitude', $val[1])->first();
                    $final->features = new OutletResource($value);
                    $collection[$key] = $final;
                    $collection->push($final);
                    $final = new stdClass();
                    break;
                }
            }
        }
        $geoJSONdata = $collection->map(function ($stop) {
            return [
                'type'       => 'Feature',
                'properties' => $stop->features,
                'geometry'   => [
                    'type'        => 'Point',
                    'coordinates' => [
                        $stop->longitude,
                        $stop->latitude,
                    ],
                ],
            ];
        });
        return response()->json([
            'type'     => 'FeatureCollection',
            'features' => $geoJSONdata
        ]);
    }
    public function stops($id)
    {
        
        $trip = Trip::find($id);
        $stops = json_decode($trip->stops_details);
        $live_data = LiveData::where('trip_id', $id)->latest()
                ->first();
        $collection = new Collection();
        $final = new stdClass();
        $i = 0;
        foreach ($stops as $key => $val) {
            $final->latitude = $val[0];
            $final->longitude = $val[1];
            
            $trip->time = date('h:i:s a', strtotime($key));
            $trip->name = Stop::where('latitude', $val[0])->where('longitude', $val[1])->first()->name;
            if(isset($live_data->latitude) && (null !== $live_data->latitude)){
                if ($live_data->latitude == $final->latitude && $live_data->longitude == $final->longitude) {
                    $final->last_updated =  '<tr><td>Arrived at '.$trip->name.' at '.date('h:i a', strtotime($live_data->time)).'</td></tr>';
                }
                else {
                    $final->last_updated = '';
                }
            }
            else {
                    $final->last_updated = '';
                }
            
            $final->features = '<div><strong>'.$trip->name.':</strong><br>'.$trip->time.'</div>';
            $final->details = '<tr><td>'.$trip->name.'</td><td>'.$trip->time.'</td></tr>';
            $collection[$i] = $final;
            $collection->push($final);
            $final = new stdClass();
            $i++;
        }
        $geoJSONdata = $collection->map(function ($stop) {
            return [
                'type'       => 'Feature',
                'properties' => $stop->features,
                'details'    => $stop->details,
                'last_updated'    => $stop->last_updated,
                'geometry'   => [
                    'type'        => 'Point',
                    'coordinates' => [
                        $stop->longitude,
                        $stop->latitude,
                    ],
                ],
            ];
        });
        return response()->json([
            'type'     => 'FeatureCollection',
            'features' => $geoJSONdata,
        ]);
    }
    public function stopslatlng($id)
    {
        
        $trip = Trip::find($id);
        $stops = json_decode($trip->stops_details);
        
        $collection = new Collection();
        $final = new stdClass();
        $i = 0;
        foreach ($stops as $key => $val) {
            $final->latitude = $val[0];
            $final->longitude = $val[1];
            
            $collection->push($final);
            $final = new stdClass();
            $i++;
        }
        return response()->json([
            'features' => $collection,
        ]);
    }
    public function updateLocation(Request $request)
    {
        /*request()->validate([
            'stopLat' => ['required'],
            'stopLat' => ['required'],
            'tripId' => ['required', 'integer'],
            'time' => ['required'],
        ]);*/
        $data = array();
        $data['latitude'] = request()->stopLat;
        $data['longitude'] = request()->stopLong;
        $data['trip_id'] = request()->trip;
        $data['time'] = date('y-m-d h:i:s', strtotime(request()->time));
        $data['accuracy'] = request()->accuracy;
        $liv_data = LiveData::create($data);
        return $liv_data;
        //return json_encode($data);
        /*var_dump($stopLat);
        echo "long";
        var_dump($stopLong);
        echo "tripid";
        var_dump($tripId);
        var_dump($time);
        echo "accuracy";
        dd($accuracy);*/
        //find stop id from stop lat and long
        //update live_data table
        //return true
    }
    public function bck(Request $request)
    {
        $outlets = Outlet::all();
        $geoJSONdata = $outlets->map(function ($outlet) {
            return [
                'type'       => 'Feature',
                'properties' => new OutletResource($outlet),
                'geometry'   => [
                    'type'        => 'Point',
                    'coordinates' => [
                        $outlet->longitude,
                        $outlet->latitude,
                    ],
                ],
            ];
        });
        return response()->json([
            'type'     => 'FeatureCollection',
            'features' => $geoJSONdata,
        ]);
    }
}

Local_bus_information_system/app/Http/Controllers/OutletController.php
<?php

namespace App\Http\Controllers;

use App\Outlet;
use Illuminate\Http\Request;

class OutletController extends Controller
{
    /**
     * Display a listing of the outlet.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $this->authorize('manage_outlet');

        $outletQuery = Outlet::query();
        $outletQuery->where('name', 'like', '%'.request('q').'%');
        $outlets = $outletQuery->paginate(25);

        return view('outlets.index', compact('outlets'));
    }

    /**
     * Show the form for creating a new outlet.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', new Outlet);

        return view('outlets.create');
    }

    /**
     * Store a newly created outlet in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $this->authorize('create', new Outlet);

        $newOutlet = $request->validate([
            'name'      => 'required|max:60',
            'address'   => 'nullable|max:255',
            'latitude'  => 'nullable|required_with:longitude|max:15',
            'longitude' => 'nullable|required_with:latitude|max:15',
        ]);
        $newOutlet['creator_id'] = auth()->id();

        $outlet = Outlet::create($newOutlet);

        return redirect()->route('outlets.show', $outlet);
    }

    /**
     * Display the specified outlet.
     *
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\View\View
     */
    public function show(Outlet $outlet)
    {
        return view('outlets.show', compact('outlet'));
    }

    /**
     * Show the form for editing the specified outlet.
     *
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\View\View
     */
    public function edit(Outlet $outlet)
    {
        $this->authorize('update', $outlet);

        return view('outlets.edit', compact('outlet'));
    }

    /**
     * Update the specified outlet in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\Routing\Redirector
     */
    public function update(Request $request, Outlet $outlet)
    {
        $this->authorize('update', $outlet);

        $outletData = $request->validate([
            'name'      => 'required|max:60',
            'address'   => 'nullable|max:255',
            'latitude'  => 'nullable|required_with:longitude|max:15',
            'longitude' => 'nullable|required_with:latitude|max:15',
        ]);
        $outlet->update($outletData);

        return redirect()->route('outlets.show', $outlet);
    }

    /**
     * Remove the specified outlet from storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Outlet  $outlet
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Request $request, Outlet $outlet)
    {
        $this->authorize('delete', $outlet);

        $request->validate(['outlet_id' => 'required']);

        if ($request->get('outlet_id') == $outlet->id && $outlet->delete()) {
            return redirect()->route('outlets.index');
        }

        return back();
    }
}

Local_bus_information_system/resources/views/outlets/edit.blade.php
@extends('layouts.app')

@section('title', __('outlet.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $outlet)
        @can('delete', $outlet)
            <div class="card">
                <div class="card-header">{{ __('outlet.delete') }}</div>
                <div class="card-body">
                    <label class="control-label text-primary">{{ __('outlet.name') }}</label>
                    <p>{{ $outlet->name }}</p>
                    <label class="control-label text-primary">{{ __('outlet.address') }}</label>
                    <p>{{ $outlet->address }}</p>
                    <label class="control-label text-primary">{{ __('outlet.latitude') }}</label>
                    <p>{{ $outlet->latitude }}</p>
                    <label class="control-label text-primary">{{ __('outlet.longitude') }}</label>
                    <p>{{ $outlet->longitude }}</p>
                    {!! $errors->first('outlet_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('outlet.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('outlets.destroy', $outlet) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="outlet_id" type="hidden" value="{{ $outlet->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('outlets.edit', $outlet) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>
        @endcan
        @else
        <div class="card">
            <div class="card-header">{{ __('outlet.edit') }}</div>
            <form method="POST" action="{{ route('outlets.update', $outlet) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('outlet.name') }}</label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $outlet->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="form-group">
                        <label for="address" class="control-label">{{ __('outlet.address') }}</label>
                        <textarea id="address" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" rows="4">{{ old('address', $outlet->address) }}</textarea>
                        {!! $errors->first('address', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="latitude" class="control-label">{{ __('outlet.latitude') }}</label>
                                <input id="latitude" type="text" class="form-control{{ $errors->has('latitude') ? ' is-invalid' : '' }}" name="latitude" value="{{ old('latitude', $outlet->latitude) }}" required>
                                {!! $errors->first('latitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="longitude" class="control-label">{{ __('outlet.longitude') }}</label>
                                <input id="longitude" type="text" class="form-control{{ $errors->has('longitude') ? ' is-invalid' : '' }}" name="longitude" value="{{ old('longitude', $outlet->longitude) }}" required>
                                {!! $errors->first('longitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                    </div>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('outlet.update') }}" class="btn btn-success">
                    <a href="{{ route('outlets.show', $outlet) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    @can('delete', $outlet)
                        <a href="{{ route('outlets.edit', [$outlet, 'action' => 'delete']) }}" id="del-outlet-{{ $outlet->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    @endcan
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

@section('styles')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>

<style>
    #mapid { height: 300px; }
</style>
@endsection

@push('scripts')
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script>
    var mapCenter = [{{ $outlet->latitude }}, {{ $outlet->longitude }}];
    var map = L.map('mapid').setView(mapCenter, {{ config('leaflet.detail_zoom_level') }});

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var marker = L.marker(mapCenter).addTo(map);
    function updateMarker(lat, lng) {
        marker
        .setLatLng([lat, lng])
        .bindPopup("Your location :  " + marker.getLatLng().toString())
        .openPopup();
        return false;
    };

    map.on('click', function(e) {
        let latitude = e.latlng.lat.toString().substring(0, 15);
        let longitude = e.latlng.lng.toString().substring(0, 15);
        $('#latitude').val(latitude);
        $('#longitude').val(longitude);
        updateMarker(latitude, longitude);
    });

    var updateMarkerByInputs = function() {
        return updateMarker( $('#latitude').val() , $('#longitude').val());
    }
    $('#latitude').on('input', updateMarkerByInputs);
    $('#longitude').on('input', updateMarkerByInputs);
</script>
@endpush

Local_bus_information_system/resources/views/outlets/mapbckp.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    @if(Session::has('warning')) 
      <div class="alert alert-danger">
        <ul>
          <li>{{Session::get('warning')}}</li>
      </ul>
    </div>
    @endif
    <div class="card-body" id="mapid"></div>

</div>
    @isset($trips)

        <div class="container pt-2">
    <div class="row">
        <table class="table table-bordered dt-responsive nowrap" id="table"  style="width:100%">


            <thead>
                <tr>
                  <th scope="col">Bus</th>
                  <th scope="col">Owned By</th>
                  <th scope="col">Number</th>
                  <th scope="col">Type</th>
                  <th scope="col">Time</th>
                  <th scope="col">Time</th>
                  <th scope="col">From</th>
                  <th scope="col">To</th>
                  <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                    @foreach($trips as $trip)
                        <tr>
                            <td> {{$trip->name}}</td>
                            <td> {{$trip->owner}}</td>
                            <td> {{$trip->number}}</td>
                            <td> {{$trip->type}}</td>
                          <td> {{date('h:i:s a', strtotime($trip->start))}}</td>
                          <td>{{date('h:i:s a', strtotime($trip->end))}}</td>
                          <td>{{$trip->origin}}</td>
                          <td>{{$trip->destination}}</td>
                          <td><button onclick="listStops({{$trip->id}})">view stops</button></td>
                        </tr>
                    @endforeach

            </tbody>
        </table>
    </div>
</div>


    @endisset
@endsection

@section('styles')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />

<style>
    #mapid { min-height: 500px; }
</style>
@endsection
@push('scripts')
<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>

<script>

    var map = L.map('mapid').setView([{{ config('leaflet.map_center_latitude') }}, {{ config('leaflet.map_center_longitude') }}], {{ config('leaflet.zoom_level') }});
    var baseUrl = "{{ url('/') }}";

    L.tileLayer('http://{s}.www.toolserver.org/tiles/bw-mapnik/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
            maxZoom: 28
        }).addTo(map);
var markerGroup = L.layerGroup().addTo(map);
    axios.get('{{ route('api.outlets.index') }}')
    .then(function (response) {
        console.log(response.data);
        L.geoJSON(response.data, {
            pointToLayer: function(geoJsonPoint, latlng) {
                return L.marker(latlng).addTo(markerGroup);
            }
        })
        .bindPopup(function (layer) {
            console.log(layer.feature.properties);
            var mpopup = '<div class="my-2"><strong>'+layer.feature.properties.name.name+':</strong><br>'+layer.feature.properties.time+'</div>'
            return mpopup;
        }).addTo(map);
    })
    .catch(function (error) {
        console.log(error);
    });
var legend = L.control({position: 'topright'});
legend.onAdd = function (map) {
    var div = L.DomUtil.create('div', 'info legend');
    div.innerHTML = '<form action="{{url("/")}}" method="POST">{{ csrf_field() }}<select name="from"><option value="" disabled selected>From</option>@foreach($stops as $stop)<option value="{{$stop->id}}">{{$stop->name}}</option>@endforeach</select><select name="to"><option value="" disabled selected>To</option>@foreach($stops as $stop)<option value="{{$stop->id}}">{{$stop->name}}</option>@endforeach</select><input type="submit" value="submit" name="listbus"></form>';
    div.firstChild.onmousedown = div.firstChild.ondblclick = L.DomEvent.stopPropagation;
    return div;
};
legend.addTo(map);
/*$('select').change(function(){
    alert('changed');
});*/
    @can('create', new App\Outlet)
    var theMarker;

    map.on('click', function(e) {
        let latitude = e.latlng.lat.toString().substring(0, 15);
        let longitude = e.latlng.lng.toString().substring(0, 15);

        if (theMarker != undefined) {
            map.removeLayer(theMarker);
        };

        var popupContent = "Your location : " + latitude + ", " + longitude + ".";
        popupContent += '<br><a href="{{ route('stops.create') }}?latitude=' + latitude + '&longitude=' + longitude + '">Add new stop here</a>';

        theMarker = L.marker([latitude, longitude]).addTo(map);
        theMarker.bindPopup(popupContent)
        .openPopup();
    });
    @endcan
</script>

<script type="text/javascript">
  route = L.Routing.control({
                    waypoints: []
                    }).addTo(map); 
    function listStops(x) {

        if(isNumber(x)) {

map.removeControl(route);
            axios.get('/api/stops/'+x)
            .then(function (result) {
                console.log(result.data);
                markerGroup.clearLayers();
                    cor = [];
                    
                var a = result.data.features;
                L.geoJSON(result.data, {
                    pointToLayer: function(geoJsonPoint, latlng) {
                      /*waypointss = L.Routing.waypoint(geoJsonPoint.geometry.coordinates[0], geoJsonPoint.geometry.coordinates[1]);*/

//console.log(geoJsonPoint.geometry.coordinates[0]);

                    

                      
                        return L.marker(latlng).addTo(markerGroup);
                    }
                })
                .bindPopup(function (result) {
                    //console.log(result.feature.properties);
                    //
                    //waypoints[] = L.latLng(result.feature.geometry.coordinates[0]
                    var mpopup = result.feature.properties;
                    return mpopup;
                }).addTo(map);
                a.forEach(function(entry, index) {
       // console.log(entry.geometry.coordinates[0]);
        cor[index] = L.latLng(entry.geometry.coordinates[1], entry.geometry.coordinates[0]);


});
            /*for(var j = 1; j < cor.length; j+=2){
                    L.Routing.control({
                    waypoints: [L.latLng(cor[j-1].lng, cor[j-1].lat),L.latLng(cor[j+1].lng, cor[j+1].lat)],show: false, createMarker: function() { return null; }}).addTo(map);  
                    /*console.log(extractedPoints[j-1], extractedPoints[j]),L.latLng(extractedPoints[j+1], extractedPoints[j+2]);*/
                    /*map.setZoom(14);
                }*/
                 route = L.Routing.control({
                    waypoints: cor
                    }).addTo(map);  
                    /*console.log(extractedPoints[j-1], extractedPoints[j]),L.latLng(extractedPoints[j+1], extractedPoints[j+2]);*/
                    map.setZoom(14);
            })
            .catch(function (error) {
                console.log(error);
            });


        }
    }

    //check numeric
    function isNumber(n) {
      return !isNaN(parseFloat(n)) && isFinite(n);
    }
</script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script type="text/javascript">
        
        $(document).ready(function() {
            var table = $('#table').DataTable( {
                fixedHeader: true
            } );
        } );
    </script>

<script src="https://unpkg.com/leaflet-ant-path" type="text/javascript"></script>
    <script type="text/javascript">

        /*var pointA = new L.LatLng(28.635308, 77.22496);
var pointB = new L.LatLng(28.984461, 77.70641);
var pointList = [pointA, pointB];

var firstpolyline = new L.Polyline(pointList, {
    color: 'red',
    weight: 3,
    opacity: 0.5,
    smoothFactor: 1
});
firstpolyline.addTo(map);
 //This is a example, the JSON can come from any place

const path = new L.Polyline.AntPath([
  [8.3943892454993, 77.104067802429],
  [8.4027131026976, 77.086064815521]], {
  "delay": 400,
  "dashArray": [
    10,
    20
  ],
  "weight": 5,
  "color": "#0000FF",
  "pulseColor": "#FFFFFF",
  "paused": false,
  "reverse": false,
  "hardwareAccelerated": true
});


map.addLayer(path);
map.fitBounds(path.getBounds());*/
    </script>
@endpush