Local_bus_information_system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'OutletMapController@index');

Route::get('/routing', 'OutletMapController@routing');

Route::post('/', 'OutletMapController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
 * Outlets Routes
 */
Route::get('/our_outlets', 'OutletMapController@index')->name('outlet_map.index');
Route::resource('outlets', 'OutletController');

/*
 * Stops Routes
 */
Route::resource('stops', 'StopController');

/*
 * Buses Routes
 */
Route::resource('buses', 'BusController');

/*
 * Trip Routes
 */
Route::resource('trips', 'TripController');

/*Route::get('/about', 'PageController@index');

Local_bus_information_system/app/Stop.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Stop extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'latitude', 'longitude',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    /*public $appends = [
        'coordinate', 'map_popup_content',
    ];*/
}

Local_bus_information_system/app/Http/Controllers/StopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Stop;

class StopController extends Controller
{
    public function __construct() {

    	$this->middleware('auth');

    }

    public function index()
    {
        $stopQuery = Stop::query();
        $stopQuery->where('name', 'like', '%'.request('q').'%');
        $stops = $stopQuery->paginate(25);
        
        //$stops = Stop::paginate(10);
        return view('stops.list', [
            'stops' => $stops
        ]);
    }

    public function create()
    {
        return view('stops.create');
    }

    public function store(Request $request)
    {

        $newStop = $request->validate([
            'name'      => 'required|max:60',
            'latitude'  => 'nullable|required_with:longitude|max:15',
            'longitude' => 'nullable|required_with:latitude|max:15',
        ]);
        //$newStop['creator_id'] = auth()->id();

        $stop = Stop::create($newStop);

        return redirect('/stops');
    }

    public function show(Stop $stop)
    {
        return view('stops.show', compact('stop'));
    }

    public function edit($stop)
    {
        $stop = Stop::find($stop);


        return view('stops.edit', [
            'stop' => $stop
        ]);
    }

    public function update(Request $request, Stop $stop)
    {

        $stopData = $request->validate([
            'name'      => 'required|max:60',
            'latitude'  => 'nullable|required_with:longitude|max:15',
            'longitude' => 'nullable|required_with:latitude|max:15',
        ]);
        $stop->update($stopData);

        return redirect('/stops');
    }

    public function destroy(Request $request, Stop $stop)
    {

        $request->validate(['stop_id' => 'required']);

        if ($request->get('stop_id') == $stop->id && $stop->delete()) {
            return redirect()->route('stops.index');
        }

        return back();
    }
}

Local_bus_information_system/resources/views/stops/create.blade.php
@extends('layouts.app')

@section('title', __('stop.create'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('stop.create') }}</div>
            <form method="POST" action="{{ route('stops.store') }}" accept-charset="UTF-8">
                {{ csrf_field() }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('stop.name') }}</label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="latitude" class="control-label">{{ __('stop.latitude') }}</label>
                                <input id="latitude" type="text" class="form-control{{ $errors->has('latitude') ? ' is-invalid' : '' }}" name="latitude" value="{{ old('latitude', request('latitude')) }}" required>
                                {!! $errors->first('latitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="longitude" class="control-label">{{ __('stop.longitude') }}</label>
                                <input id="longitude" type="text" class="form-control{{ $errors->has('longitude') ? ' is-invalid' : '' }}" name="longitude" value="{{ old('longitude', request('longitude')) }}" required>
                                {!! $errors->first('longitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                    </div>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('stop.create') }}" class="btn btn-success">
                    <a href="{{ route('stops.index') }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>

<style>
    #mapid { height: 300px; }
</style>
@endsection

@push('scripts')
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script>
    var mapCenter = [{{ request('latitude', config('leaflet.map_center_latitude')) }}, {{ request('longitude', config('leaflet.map_center_longitude')) }}];
    var map = L.map('mapid').setView(mapCenter, {{ config('leaflet.zoom_level') }});

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var marker = L.marker(mapCenter).addTo(map);
    function updateMarker(lat, lng) {
        marker
        .setLatLng([lat, lng])
        .bindPopup("Your location :  " + marker.getLatLng().toString())
        .openPopup();
        return false;
    };

    map.on('click', function(e) {
        let latitude = e.latlng.lat.toString().substring(0, 15);
        let longitude = e.latlng.lng.toString().substring(0, 15);
        $('#latitude').val(latitude);
        $('#longitude').val(longitude);
        updateMarker(latitude, longitude);
    });

    var updateMarkerByInputs = function() {
        return updateMarker( $('#latitude').val() , $('#longitude').val());
    }
    $('#latitude').on('input', updateMarkerByInputs);
    $('#longitude').on('input', updateMarkerByInputs);
</script>
@endpush

Local_bus_information_system/resources/views/stops/edit.blade.php
@extends('layouts.app')

@section('title', __('stop.edit'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        @if (request('action') == 'delete' && $stop)

            <div class="card">
                <div class="card-header">{{ __('stop.delete') }}</div>
                <div class="card-body">
                    <label class="control-label text-primary">{{ __('stop.name') }}</label>
                    <p>{{ $stop->name }}</p>
                    <label class="control-label text-primary">{{ __('stop.latitude') }}</label>
                    <p>{{ $stop->latitude }}</p>
                    <label class="control-label text-primary">{{ __('stop.longitude') }}</label>
                    <p>{{ $stop->longitude }}</p>
                    {!! $errors->first('stop_id', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                </div>
                <hr style="margin:0">
                <div class="card-body text-danger">{{ __('stop.delete_confirm') }}</div>
                <div class="card-footer">
                    <form method="POST" action="{{ route('stops.destroy', $stop) }}" accept-charset="UTF-8" onsubmit="return confirm(&quot;{{ __('app.delete_confirm') }}&quot;)" class="del-form float-right" style="display: inline;">
                        {{ csrf_field() }} {{ method_field('delete') }}
                        <input name="stop_id" type="hidden" value="{{ $stop->id }}">
                        <button type="submit" class="btn btn-danger">{{ __('app.delete_confirm_button') }}</button>
                    </form>
                    <a href="{{ route('stops.edit', $stop) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                </div>
            </div>

        @else
        <div class="card">
            <div class="card-header">{{ __('stop.edit') }}</div>
            <form method="POST" action="{{ route('stops.update', $stop) }}" accept-charset="UTF-8">
                {{ csrf_field() }} {{ method_field('patch') }}
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="control-label">{{ __('stop.name') }}</label>
                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $stop->name) }}" required>
                        {!! $errors->first('name', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="latitude" class="control-label">{{ __('stop.latitude') }}</label>
                                <input id="latitude" type="text" class="form-control{{ $errors->has('latitude') ? ' is-invalid' : '' }}" name="latitude" value="{{ old('latitude', $stop->latitude) }}" required>
                                {!! $errors->first('latitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="longitude" class="control-label">{{ __('stop.longitude') }}</label>
                                <input id="longitude" type="text" class="form-control{{ $errors->has('longitude') ? ' is-invalid' : '' }}" name="longitude" value="{{ old('longitude', $stop->longitude) }}" required>
                                {!! $errors->first('longitude', '<span class="invalid-feedback" role="alert">:message</span>') !!}
                            </div>
                        </div>
                    </div>
                    <div id="mapid"></div>
                </div>
                <div class="card-footer">
                    <input type="submit" value="{{ __('stop.update') }}" class="btn btn-success">
                    <a href="{{ route('stops.show', $stop) }}" class="btn btn-link">{{ __('app.cancel') }}</a>
                    
                        <a href="{{ route('stops.edit', [$stop, 'action' => 'delete']) }}" id="del-stop-{{ $stop->id }}" class="btn btn-danger float-right">{{ __('app.delete') }}</a>
                    
                </div>
            </form>
        </div>
    </div>
</div>
@endif
@endsection

@section('styles')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>

<style>
    #mapid { height: 300px; }
</style>
@endsection

@push('scripts')
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>
<script>
    var mapCenter = [{{ $stop->latitude }}, {{ $stop->longitude }}];
    var map = L.map('mapid').setView(mapCenter, {{ config('leaflet.detail_zoom_level') }});

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var marker = L.marker(mapCenter).addTo(map);
    function updateMarker(lat, lng) {
        marker
        .setLatLng([lat, lng])
        .bindPopup("Your location :  " + marker.getLatLng().toString())
        .openPopup();
        return false;
    };

    map.on('click', function(e) {
        let latitude = e.latlng.lat.toString().substring(0, 15);
        let longitude = e.latlng.lng.toString().substring(0, 15);
        $('#latitude').val(latitude);
        $('#longitude').val(longitude);
        updateMarker(latitude, longitude);
    });

    var updateMarkerByInputs = function() {
        return updateMarker( $('#latitude').val() , $('#longitude').val());
    }
    $('#latitude').on('input', updateMarkerByInputs);
    $('#longitude').on('input', updateMarkerByInputs);
</script>
@endpush

Local_bus_information_system/resources/views/stops/list.blade.php
@extends('layouts.app')

@section('title', __('stop.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
            <a href="{{ route('stops.create') }}" class="btn btn-success">{{ __('stop.create') }}</a>
    </div>
    <h1 class="page-title">{{ __('stop.list') }} <small>{{ __('app.total') }} : {{ $stops->total() }} {{ __('stop.stop') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="control-label">{{ __('stop.search') }}</label>
                        <input placeholder="{{ __('stop.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('stop.search') }}" class="btn btn-secondary">
                    <a href="{{ route('stops.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('stop.name') }}</th>
                        <th>{{ __('stop.latitude') }}</th>
                        <th>{{ __('stop.longitude') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($stops as $key => $stop)
                    <tr>
                        <td class="text-center">{{ $stops->firstItem() + $key }}</td>
                        <td>{!! $stop->name !!}</td>
                        <td>{{ $stop->latitude }}</td>
                        <td>{{ $stop->longitude }}</td>
                        <td class="text-center">
                            <a href="{{ route('stops.show', $stop) }}" id="show-outlet-{{ $stop->id }}">{{ __('app.show') }}</a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $stops->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection

Local_bus_information_system/resources/views/stops/show.blade.php
@extends('layouts.app')

@section('title', __('stop.detail'))

@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ __('stop.detail') }}</div>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>
                        <tr><td>{{ __('stop.name') }}</td><td>{{ $stop->name }}</td></tr>
                        <tr><td>{{ __('stop.latitude') }}</td><td>{{ $stop->latitude }}</td></tr>
                        <tr><td>{{ __('stop.longitude') }}</td><td>{{ $stop->longitude }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                    <a href="{{ route('stops.edit', $stop) }}" id="edit-outlet-{{ $stop->id }}" class="btn btn-warning">{{ __('stop.edit') }}</a>
                <a href="{{ route('stops.index') }}" class="btn btn-link">{{ __('stop.back_to_index') }}</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">{{ trans('stop.location') }}</div>
            @if ($stop->longitude)
            <div class="card-body" id="mapid"></div>
            @else
            <div class="card-body">{{ __('stop.no_coordinate') }}</div>
            @endif
        </div>
    </div>
</div>
@endsection

@section('styles')
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>

<style>
    #mapid { height: 400px; }
</style>
@endsection
@push('scripts')
<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>

<script>
    var map = L.map('mapid').setView([{{ $stop->latitude }}, {{ $stop->longitude }}], {{ config('leaflet.detail_zoom_level') }});

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    L.marker([{{ $stop->latitude }}, {{ $stop->longitude }}]).addTo(map)
        .bindPopup('{!! $stop->map_popup_content !!}');
</script>
@endpush